name: groupscholar_resource_usage_ledger
description: CLI to log and summarize Group Scholar resource usage in Postgres.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.9

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  args: ^2.7.0
  postgres: ^3.5.9
  intl: ^0.20.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
